# DLDC Project Dataviewer
## Load the Data

In [70]:
import pandas as pd
import numpy as np

unit = ['unit_number','time']
settings = ['operational_setting 1','operational_setting 2','operational_setting 3']
sensors = [f"sensor_{i}" for i in range(1, 22)]

columns = unit+settings+sensors
pwd = './data/'

# Load data for FD001
train_FD001 = pd.read_csv(pwd+'train_FD001.txt', delimiter=' ', header=None, index_col=False, names=columns)
test_FD001 = pd.read_csv(pwd+'test_FD001.txt', delimiter=' ', header=None, index_col=False, names=columns)
RUL_FD001 = pd.read_csv(pwd+'RUL_FD001.txt', header=None)


# Load data for FD002
train_FD002 = pd.read_csv(pwd+'train_FD002.txt', delimiter=' ', header=None, index_col=False, names=columns)
test_FD002 = pd.read_csv(pwd+'test_FD002.txt', delimiter=' ', header=None, index_col=False, names=columns)
RUL_FD002 = pd.read_csv(pwd+'RUL_FD002.txt', header=None)

# Load data for FD003
train_FD003 = pd.read_csv(pwd+'train_FD003.txt', delimiter=' ', header=None, index_col=False, names=columns)
test_FD003 = pd.read_csv(pwd+'test_FD003.txt', delimiter=' ', header=None, index_col=False, names=columns)
RUL_FD003 = pd.read_csv(pwd+'RUL_FD003.txt', header=None)

# Load data for FD004
train_FD004 = pd.read_csv(pwd+'train_FD004.txt', delimiter=' ', header=None, index_col=False, names=columns)
test_FD004 = pd.read_csv(pwd+'test_FD004.txt', delimiter=' ', header=None, index_col=False, names=columns)
RUL_FD004 = pd.read_csv(pwd+'RUL_FD004.txt', header=None)

# Add unit names to RUL
for RUL in [RUL_FD001, RUL_FD002, RUL_FD003, RUL_FD004]:
    RUL.insert(0, '-', [unit_name for unit_name in range(1,RUL.shape[0]+1)], True)
    RUL.columns = [unit[0],'RUL']

C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:12: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  train_FD001 = pd.read_csv(pwd+'train_FD001.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:13: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  test_FD001 = pd.read_csv(pwd+'test_FD001.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:18: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  train_FD002 = pd.read_csv(pwd+'train_FD002.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:19: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  test_FD002 = pd.read_csv(pwd+'test_FD002.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  train_FD003 = pd.read_csv(pwd+'train_FD003.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:24: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  test_FD003 = pd.read_csv(pwd+'test_FD003.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:28: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  train_FD004 = pd.read_csv(pwd+'train_FD004.txt', delimiter=' ', header=None, index_col=False, names=columns)
C:\Users\kleme\AppData\Local\Temp\ipykernel_20280\3430439659.py:29: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  test_FD004 = pd.read_csv(pwd+'test_FD004.txt', delimiter=' ', header=None, index_col=False, names=columns)

In [49]:
train_FD001.head(10)

,unit_number,time,operational_setting 1,operational_setting 2,operational_setting 3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
5,1,6,-0.0043,-0.0001,100.0,518.67,642.10,1584.47,1398.37,14.62,...,521.68,2388.03,8132.85,8.4108,0.03,391,2388,100.0,38.98,23.3669
6,1,7,0.0010,0.0001,100.0,518.67,642.48,1592.32,1397.77,14.62,...,522.32,2388.03,8132.32,8.3974,0.03,392,2388,100.0,39.10,23.3774
7,1,8,-0.0034,0.0003,100.0,518.67,642.56,1582.96,1400.97,14.62,...,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100.0,38.97,23.3106
8,1,9,0.0008,0.0001,100.0,518.67,642.12,1590.98,1394.80,14.62,...,521.79,2388.05,8125.69,8.3728,0.03,392,2388,100.0,39.05,23.4066
9,1,10,-0.0033,0.0001,100.0,518.67,641.71,1591.24,1400.46,14.62,...,521.79,2388.06,8129.38,8.4286,0.03,393,2388,100.0,38.95,23.4694

In [50]:
train_FD001.tail(10)

,unit_number,time,operational_setting 1,operational_setting 2,operational_setting 3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
20621,100,191,-0.0005,-0.0000,100.0,518.67,643.69,1610.87,1427.19,14.62,...,519.80,2388.28,8143.56,8.5092,0.03,398,2388,100.0,38.39,23.1218
20622,100,192,-0.0009,0.0001,100.0,518.67,643.53,1601.23,1419.48,14.62,...,520.59,2388.21,8143.46,8.4892,0.03,397,2388,100.0,38.56,23.0770
20623,100,193,-0.0001,0.0002,100.0,518.67,643.09,1599.81,1428.93,14.62,...,520.11,2388.19,8142.02,8.5424,0.03,397,2388,100.0,38.47,23.0230
20624,100,194,-0.0011,0.0003,100.0,518.67,643.72,1597.29,1427.41,14.62,...,519.55,2388.22,8139.67,8.5215,0.03,394,2388,100.0,38.38,23.1324
20625,100,195,-0.0002,-0.0001,100.0,518.67,643.41,1600.04,1431.90,14.62,...,519.71,2388.28,8142.90,8.5519,0.03,394,2388,100.0,38.14,23.1923
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [51]:
train_FD001.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
unit_number,20631.0,51.506568,2.922763e+01,1.0000,26.0000,52.0000,77.0000,100.0000
time,20631.0,108.807862,6.888099e+01,1.0000,52.0000,104.0000,156.0000,362.0000
operational_setting 1,20631.0,-0.000009,2.187313e-03,-0.0087,-0.0015,0.0000,0.0015,0.0087
operational_setting 2,20631.0,0.000002,2.930621e-04,-0.0006,-0.0002,0.0000,0.0003,0.0006
operational_setting 3,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
sensor_1,20631.0,518.670000,0.000000e+00,518.6700,518.6700,518.6700,518.6700,518.6700
sensor_2,20631.0,642.680934,5.000533e-01,641.2100,642.3250,642.6400,643.0000,644.5300
sensor_3,20631.0,1590.523119,6.131150e+00,1571.0400,1586.2600,1590.1000,1594.3800,1616.9100
sensor_4,20631.0,1408.933782,9.000605e+00,1382.2500,1402.3600,1408.0400,1414.5550,1441.4900
sensor_5,20631.0,14.620000,1.776400e-15,14.6200,14.6200,14.6200,14.6200,14.6200
sensor_6,20631.0,21.609803,1.388985e-03,21.6000,21.6100,21.6100,21.6100,21.6100
sensor_7,20631.0,553.367711,8.850923e-01,549.8500,552.8100,553.4400,554.0100,556.0600
sensor_8,20631.0,2388.096652,7.098548e-02,2387.9000,2388.0500,2388.0900,2388.1400,2388.5600
sensor_9,20631.0,9065.242941,2.208288e+01,9021.7300,9053.1000,9060.6600,9069.4200,9244.5900
sensor_10,20631.0,1.300000,0.000000e+00,1.3000,1.3000,1.3000,1.3000,1.3000
sensor_11,20631.0,47.541168,2.670874e-01,46.8500,47.3500,47.5100,47.7000,48.5300
sensor_12,20631.0,521.413470,7.375534e-01,518.6900,520.9600,521.4800,521.9500,523.3800
sensor_13,20631.0,2388.096152,7.191892e-02,2387.8800,2388.0400,2388.0900,2388.1400,2388.5600
sensor_14,20631.0,8143.752722,1.907618e+01,8099.9400,8133.2450,8140.5400,8148.3100,8293.7200
sensor_15,20631.0,8.442146,3.750504e-02,8.3249,8.4149,8.4389,8.4656,8.5848
sensor_16,20631.0,0.030000,1.387812e-17,0.0300,0.0300,0.0300,0.0300,0.0300
sensor_17,20631.0,393.210654,1.548763e+00,388.0000,392.0000,393.0000,394.0000,400.0000
sensor_18,20631.0,2388.000000,0.000000e+00,2388.0000,2388.0000,2388.0000,2388.0000,2388.0000
sensor_19,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
sensor_20,20631.0,38.816271,1.807464e-01,38.1400,38.7000,38.8300,38.9500,39.4300
sensor_21,20631.0,23.289705,1.082509e-01,22.8942,23.2218,23.2979,23.3668,23.6184

In [56]:
test_FD001.mean()
test_FD001.nunique()
train_FD001.dtypes
train_FD001.sensor_2.value_counts()

sensor_2
642.50    190
642.56    189
642.53    188
642.60    184
642.67    179
         ...
641.31      1
644.47      1
644.35      1
644.50      1
644.39      1
Name: count, Length: 310, dtype: int64

In [53]:
for num,df in enumerate([train_FD001, test_FD001, RUL_FD001, 
                         train_FD002, test_FD002, RUL_FD002, 
                         train_FD003, test_FD003, RUL_FD003, 
                         train_FD004, test_FD004, RUL_FD004]):
    print(f"NaN values in dataframe {num}: ",(df.isna().transpose() == True).all().sum())

# No missing values!

NaN values in dataframe 0:  0
NaN values in dataframe 1:  0
NaN values in dataframe 2:  0
NaN values in dataframe 3:  0
NaN values in dataframe 4:  0
NaN values in dataframe 5:  0
NaN values in dataframe 6:  0
NaN values in dataframe 7:  0
NaN values in dataframe 8:  0
NaN values in dataframe 9:  0
NaN values in dataframe 10:  0
NaN values in dataframe 11:  0

In [65]:
train_FD001.loc[lambda df: df['unit_number'] == 1, :]

,unit_number,time,operational_setting 1,operational_setting 2,operational_setting 3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,1,188,-0.0067,0.0003,100.0,518.67,643.75,1602.38,1422.78,14.62,...,519.79,2388.23,8117.69,8.5207,0.03,396,2388,100.0,38.51,22.9588
188,1,189,-0.0006,0.0002,100.0,518.67,644.18,1596.17,1428.01,14.62,...,519.58,2388.33,8117.51,8.5183,0.03,395,2388,100.0,38.48,23.1127
189,1,190,-0.0027,0.0001,100.0,518.67,643.64,1599.22,1425.95,14.62,...,520.04,2388.35,8112.58,8.5223,0.03,398,2388,100.0,38.49,23.0675
190,1,191,-0.0000,-0.0004,100.0,518.67,643.34,1602.36,1425.77,14.62,...,519.57,2388.30,8114.61,8.5174,0.03,394,2388,100.0,38.45,23.1295
191,1,192,0.0009,-0.0000,100.0,518.67,643.54,1601.41,1427.20,14.62,...,520.08,2388.32,8110.93,8.5113,0.03,396,2388,100.0,38.48,22.9649